version: '3.8'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  
volumes:
  db:
    driver: local

    

