import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import DetailedList from "~/components/Lists/DetailedList";
import Menu from "~/components/Menu/Menu";
import ListPostsContainer from "~/components/PostContainers/ListPostsContainer";
import Layout from "~/components/common/Layout";
import ListHeader from "~/components/headers/ListHeader";
import { api } from "~/utils/api";

export default function ListPage() {
  const router = useRouter();
  const { id } = router.query;
  const fetchList = api.list.fetch.useQuery(
    { listId: id as string },
    { enabled: id != undefined },
  );

  const { data: session, status } = useSession();

  if (status === "loading") {
    return <p>Loading...</p>;
  }

  if (status === "unauthenticated") {
    router.push("/auth/login").then();
  }

  if (!session?.user.username) {
    router.push("/auth/complete-signup").then();
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout
        menu={<Menu />}
        main={
          <div className="h-full">
            <ListHeader list={fetchList.data!} />
            <DetailedList list={fetchList.data!} />
            <ListPostsContainer listId={id as string} />
          </div>
        }
        sidebar={
          <div>
            <div className="h-screen w-full">Recommended</div>
            <div className="sticky top-0 h-screen w-full bg-blue-200">
              TRENDS
            </div>
          </div>
        }
      />
    </>
  );
}
