import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import Layout from "~/components/Layout";
import Post from "~/components/Main/Post/Post";
import Navbar from "~/components/Navbar/Navbar";
import Sidebar from "~/components/Sidebar/Sidebar";
import Header from "~/components/common/Header";
import { api } from "~/utils/api";

type Props = {};

const TweetPage = (props: Props) => {
  const router = useRouter();
  const postId = router.query.id as string;
  const { data } = api.post.fetchPost.useQuery(
    { postId },
    {
      enabled: postId !== undefined,
    }
  );
  const { data: session, status } = useSession();

  if (status === "loading") {
    return <p>Loading...</p>;
  }

  if (status === "unauthenticated") {
    router.push(`/signin?redirect=${router.asPath}`);
    return <p>Access Denied</p>;
  }

  if (!session?.user.isRegistered) {
    router.push("/register?redirect=/");
  }

  if (!data) {
    return <div>Loading...</div>;
  }
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Navbar />
        <div>
          <Header>
            <div className="text-xl font-bold">Post</div>
          </Header>
          <Post post={data} detailed />
        </div>
        <Sidebar />
      </Layout>
    </>
  );
};

export default TweetPage;
