import Head from "next/head";
import React from "react";
import BookmarkList from "~/components/BookmarkList";
import Menu from "~/components/Menu/Menu";
import Layout from "~/components/common/Layout";
import BookmarkHeader from "~/components/headers/BookmarkHeader";
import { api } from "~/utils/api";

type Props = {};

const Bookmarks = (props: Props) => {
  const fetchBookmarkLists = api.bookmark.fetchBookmarkLists.useQuery();
  const fetchBookmarks = api.bookmark.fetchBookmarks.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout
        menu={<Menu />}
        main={
          <div className="h-full">
            <BookmarkHeader />
            {fetchBookmarkLists.data?.map((list) => (
              <BookmarkList
                key={list.id}
                name={list.name}
                bookmarks={
                  fetchBookmarks.data?.filter((b) => list.id == b.listId) || []
                }
              />
            ))}
          </div>
        }
        sidebar={
          <div>
            <div className="h-screen w-full">Recommended</div>
            <div className="sticky top-0 h-screen w-full bg-blue-200">
              TRENDS
            </div>
          </div>
        }
      />
    </>
  );
};

export default Bookmarks;
