import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import Layout from "~/components/Layout";
import Navbar from "~/components/Navbar/Navbar";
import { api } from "~/utils/api";
import { RiSearchLine } from "react-icons/ri";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Navbar />
        <div className="border-x border-gray-400 bg-gray-900">
          <header>
            <div className="flex">
              <div>Avatar</div>
              <div>Logo</div>
            </div>
            <div className="flex">
              <button>For you</button>
              <button>Following</button>
            </div>
          </header>
          <div className="h-screen">a</div>
          <div className="h-screen">a</div>
          <div className="h-screen">a</div>
        </div>
        <div className=" bg-gray-300">
          <form className="relative">
            <RiSearchLine className="absolute left-0 top-0 ml-1 mt-1" />
            <input
              className="w-full pl-6"
              type="search"
              placeholder="Search..."
            ></input>
          </form>
          <div className="h-screen">a</div>
          <div className="h-screen">a</div>
        </div>
      </Layout>
    </>
  );
}
