import { useContext, useRef } from "react";
import Head from "next/head";
import Layout from "~/components/Layout";
import Navbar from "~/components/Navbar/Navbar";
import { RiSearchLine } from "react-icons/ri";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";
import Xlogo from "~/components/Xlogo";
import { NavbarContext } from "~/context/NavbarContext";
import Tabs from "~/components/common/Tabs/Tabs";
import MainPageHeader from "~/components/Main/MainPageHeader";
import CreatePostForm from "~/components/Main/CreatePostForm";
import ForYouContainer from "~/components/Main/Containers/ForYouContainer";
import FollowingContainer from "~/components/Main/Containers/FollowingContainer";

export default function Home() {
  const router = useRouter();

  const { data: session, status } = useSession();

  const ref = useRef<HTMLDivElement>(null);

  if (status === "loading") {
    return <p>Loading...</p>;
  }

  if (status === "unauthenticated") {
    router.push("/signin?redirect=/");
    return <p>Access Denied</p>;
  }

  if (!session?.user.isRegistered) {
    router.push("/register?redirect=/");
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Navbar />
        <div className="bg-white ">
          <MainPageHeader containerRef={ref}>
            <ForYouContainer />
            <FollowingContainer />
          </MainPageHeader>
          <div ref={ref} className="mt-4 h-[500vh]">
            <CreatePostForm />
            {/* this is where for you and following are portalled */}
          </div>
        </div>
        <div className=" bg-white">
          <form className="sticky top-3 mt-3  rounded-full border border-white focus-within:border-blue-500">
            <label>
              <input
                className="peer w-full rounded-full p-3 pl-12 outline-none"
                type="search"
                placeholder="Search..."
              ></input>
              <RiSearchLine className="absolute left-0 top-0 ml-3 mt-[14px] h-5 w-5 peer-focus:text-blue-500 " />
              {/* TODO: add suggestions */}
            </label>
          </form>
          <div className="h-[200vh]">a</div>
        </div>
      </Layout>
    </>
  );
}
