import Head from "next/head";
import React from "react";
import Menu from "~/components/Menu/Menu";
import Layout from "~/components/common/Layout";
import ExploreHeader from "~/components/headers/ExploreHeader/ExploreHeader";
import SearchIcon from "~/components/icons/SearchIcon";

type Props = {};

const ExplorePage = (props: Props) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout
        menu={<Menu />}
        main={
          <div className="h-full">
            <ExploreHeader />
            <div>Trends</div>
          </div>
        }
        sidebar={
          <div>
            <div className="h-screen w-full">Recommended</div>
            <div className="sticky top-0 h-screen w-full bg-blue-200">
              TRENDS
            </div>
          </div>
        }
      />
    </>
  );
};

export default ExplorePage;
