import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import Menu from "~/components/Menu/Menu";
import Profile from "~/components/Profile/Profile";
import Layout from "~/components/common/Layout";
import BackHeader from "~/components/headers/BackHeader";
import { api } from "~/utils/api";

type Props = {};

const ProfilePage = (props: Props) => {
  const router = useRouter();
  const { username } = router.query;
  const profile = api.user.fetchProfile.useQuery(
    { username: username as string },
    { enabled: username != undefined },
  );

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout
        menu={<Menu />}
        main={
          profile.data ? (
            <div className="h-full">
              <BackHeader>
                <div className="flex flex-col">
                  <span className="text-xl font-semibold text-grayText">
                    {profile.data?.displayName}
                  </span>
                  <span className="text-13px text-lightGrayText">
                    {0} posts
                  </span>
                </div>
              </BackHeader>
              <Profile profile={profile.data} />
            </div>
          ) : (
            <div>Loading...</div>
          )
        }
        sidebar={
          <div>
            <div className="h-screen w-full">Recommended</div>
            <div className="sticky top-0 h-screen w-full bg-blue-200">
              TRENDS
            </div>
          </div>
        }
      />
    </>
  );
};

export default ProfilePage;
