import Head from "next/head";
import { useRouter } from "next/router";
import React, { useContext } from "react";
import Menu from "~/components/Menu/Menu";
import ProfileHighlightsContainer from "~/components/PostContainers/ProfileHighlightsContainer";
import ProfileLikesContainer from "~/components/PostContainers/ProfileLikesContainer";
import ProfilePostsContainer from "~/components/PostContainers/ProfilePostsContainer";
import ProfileRepliesContainer from "~/components/PostContainers/ProfileRepliesContainer";
import Profile from "~/components/Profile/Profile";
import Layout from "~/components/common/Layout";
import { MainContext, ProfilePageTabs } from "~/components/context/MainContext";
import BackHeader from "~/components/headers/BackHeader";
import { api } from "~/utils/api";

type Props = {};

const ProfilePage = (props: Props) => {
  const router = useRouter();
  const { username } = router.query;
  const profile = api.user.fetchProfile.useQuery(
    { username: username as string },
    { enabled: username != undefined },
  );

  const { profilePageSelectedTab, setProfilePageSelectedTab } =
    useContext(MainContext);

  if (!profile.data) {
    return <>Loading</>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout
        menu={<Menu />}
        main={
          profile.data ? (
            <div className="h-full">
              <BackHeader>
                <div className="flex flex-col">
                  <span className="text-xl font-semibold text-grayText">
                    {profile.data?.displayName}
                  </span>
                  <span className="text-13px text-lightGrayText">
                    {0} posts
                  </span>
                </div>
              </BackHeader>
              <Profile profile={profile.data!} />
              {profilePageSelectedTab == ProfilePageTabs.Posts && (
                <ProfilePostsContainer
                  pinnedPost={
                    profile.data.pinnedPost
                      ? profile.data.pinnedPost
                      : undefined
                  }
                  username={username as string}
                />
              )}
              {profilePageSelectedTab == ProfilePageTabs.Replies && (
                <ProfileRepliesContainer username={username as string} />
              )}
              {profilePageSelectedTab == ProfilePageTabs.Highlights && (
                <ProfileHighlightsContainer username={username as string} />
              )}
              {profilePageSelectedTab == ProfilePageTabs.Media && (
                <div>Media</div>
              )}
              {profilePageSelectedTab == ProfilePageTabs.Likes && (
                <ProfileLikesContainer username={username as string} />
              )}
            </div>
          ) : (
            <div>Loading...</div>
          )
        }
        sidebar={
          <div>
            <div className="h-screen w-full">Recommended</div>
            <div className="sticky top-0 h-screen w-full bg-blue-200">
              TRENDS
            </div>
          </div>
        }
      />
    </>
  );
};

export default ProfilePage;
